inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  Exclude:
    - 'bin/**/*'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'config/spring.rb'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'tmp/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/migrate/20191215144502_create_active_storage_tables.active_storage.rb'

Style/GlobalVars:
  AllowedVariables:
    - $redis
    - $elasticsearch
    - $rollout

Style/Documentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - lib/tasks/**/*
    - ./**/concerns/*

Layout/LineLength:
  Max: 120

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
